### ISSUE TITLE
Quickstart python from local install errors on init

### ISSUE THREAD

**Issue by samos123** [Scale3-Labs/langtrace#257]
```
Traceback (most recent call last):
  File "/home/samos/workspace/kubeai/docs/langtrace.py", line 1, in <module>
    from langtrace_python_sdk import langtrace
  File "/home/samos/workspace/kubeai/.venv/lib/python3.12/site-packages/langtrace_python_sdk/__init__.py", line 17, in <module>
    from langtrace_python_sdk import langtrace
  File "/home/samos/workspace/kubeai/.venv/lib/python3.12/site-packages/langtrace_python_sdk/langtrace.py", line 27, in <module>
    from langtrace_python_sdk.utils.langtrace_sampler import LangtraceSampler
  File "/home/samos/workspace/kubeai/.venv/lib/python3.12/site-packages/langtrace_python_sdk/utils/__init__.py", line 4, in <module>
    from langtrace.trace_attributes import SpanAttributes
  File "/home/samos/workspace/kubeai/docs/langtrace.py", line 8, in <module>
    langtrace.init(
    ^^^^^^^^^^^^^^
AttributeError: partially initialized module 'langtrace_python_sdk.langtrace' has no attribute 'init' (most likely due to a circular import)
```

My code:
```
from langtrace_python_sdk import langtrace
from langtrace_python_sdk.utils.with_root_span import with_langtrace_root_span
# Paste this code after your langtrace init function

from openai import OpenAI
api_key="snip"

langtrace.init(
    api_key=api_key
)

base_url = "http://localhost:8001/openai/v1"

@with_langtrace_root_span()
def example():
    client = OpenAI(base_url=base_url, api_key="ignored-by-kubeai")
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "How many states of matter are there?"
            }
        ],
    )
    print(response.choices[0].message.content)

example()

```

**Comment by samos123** [comment]
Turns out the issue was because my file was also called langtrace.py
