### ISSUE TITLE
Traces are sent to a Docker Compose self-hosted  LangTrace deployment, but are not displayed

### ISSUE THREAD

**Issue by lmorandini** [Scale3-Labs/langtrace#321]
I successfully deployed LangTrace 0.1.0 with Docker Compose on port 3000, created a project and generated an API key.

I then tried this sample code (`LANGTRACE_API_KEY` is the generated API key and `LANGTRACE_API_URL` is `http://localhost:3000/api/trace`).

```
import os
from langtrace_python_sdk import langtrace
from langtrace_python_sdk.utils.with_root_span import with_langtrace_root_span
from openai import OpenAI

langtrace.init(api_key=os.getenv('LANGTRACE_API_KEY'),
               api_host=os.getenv('LANGTRACE_API_URL'))

@with_langtrace_root_span()
def example():
    client = OpenAI()
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "How many states of matter are there?"
            }
        ],
    )
    print(response.choices[0].message.content)

example()
```

However no trace is shown in LangTrace, and when I use NGREP to log the traffic to port 3000, this is shown:
```
T 127.0.0.1:38024 -> 127.0.0.1:3000 [AP] #4
  POST /api/trace HTTP/1.1..Host: localhost:3000..User-Agent: OTel-OTLP-Expor
  ter-Python/1.27.0..Accept-Encoding: gzip, deflate..Accept: */*..Connection:
   keep-alive..x-api-key: 7e758d1e57e90168fe85f8feafab61169fe671af0825264c20d
  331929aefd6df..Content-Type: application/x-protobuf..Content-Length: 1264..
  ..                                                                         
##
T 127.0.0.1:38024 -> 127.0.0.1:3000 [AP] #6
  ......."..telemetry.sdk.language....python.%..telemetry.sdk.name....opentel
  emetry.!..telemetry.sdk.version....1.27.0....service.name....test.py....=.;
  langtrace_python_sdk.instrumentation.openai.instrumentation.....t..7)Z7.F@!
  .`Y....8 q.J...".........*.openai.chat.completions.create0.9H.......A.]4_..
  ..J"..langtrace.service.name....OpenAIJ...langtrace.service.type....llmJ%..
  langtrace.service.version....1.43.0J...langtrace.version....3.3.0J,..langtr
  ace.sdk.name....langtrace-python-sdkJ(..url.full....https://api.openai.com/
  v1/J...url.path..../chat/completionsJ...gen_ai.operation.name....chatJ'..ge
  n_ai.request.model....gpt-3.5-turboJ...gen_ai.system....openaiJ-..gen_ai.re
  sponse.model....gpt-3.5-turbo-0125J...gen_ai.usage.input_tokens....J ..gen_
  ai.usage.output_tokens....J...gen_ai.usage.total_tokens...&Z|...........gen
  _ai.content.prompt.Z..gen_ai.prompt.I.G[{"role": "system", "content": "How 
  many states of matter are there?"}]Z... .2_......gen_ai.content.completion.
  ....gen_ai.completion......[{"role": "assistant", "content": "There are fiv
  e states of matter: solid, liquid, gas, plasma, and Bose-Einstein condensat
  e."}]z..........z.+.)langtrace_python_sdk.utils.with_root_span.K..t..7)Z7.F
  @!.`Y............*.LangtraceRootSpan0.9........A..8_....z.......           
########
T 172.240.1.1:37074 -> 172.240.1.4:3000 [AP] #14
  POST /api/trace HTTP/1.1..Host: localhost:3000..User-Agent: OTel-OTLP-Expor
  ter-Python/1.27.0..Accept-Encoding: gzip, deflate..Accept: */*..Connection:
   keep-alive..x-api-key: 7e758d1e57e90168fe85f8feafab61169fe671af0825264c20d
  331929aefd6df..Content-Type: application/x-protobuf..Content-Length: 1264..
  ........."..telemetry.sdk.language....python.%..telemetry.sdk.name....opent
  elemetry.!..telemetry.sdk.version....1.27.0....service.name....test.py....=
  .;langtrace_python_sdk.instrumentation.openai.instrumentation.....t..7)Z7.F
  @!.`Y....8 q.J...".........*.openai.chat.completions.create0.9H.......A.]4_
  ....J"..langtrace.service.name....OpenAIJ...langtrace.service.type....llmJ%
  ..langtrace.service.version....1.43.0J...langtrace.version....3.3.0J,..lang
  trace.sdk.name....langtrace-python-sdkJ(..url.full....https://api.openai.co
  m/v1/J...url.path..../chat/completionsJ...gen_ai.operation.name....chatJ'..
  gen_ai.request.model....gpt-3.5-turboJ...gen_ai.system....openaiJ-..gen_ai.
  response.model....gpt-3.5-turbo-0125J...gen_ai.usage.input_tokens....J ..ge
  n_ai.usage.output_tokens....J...gen_ai.usage.total_tokens...&Z|...........g
  en_ai.content.prompt.Z..gen_ai.prompt.I.G[{"role": "system", "content": "Ho
  w many states of matter are there?"}]Z... .2_......gen_ai.content.completio
  n.....gen_ai.completion......[{"role": "assistant", "content": "There are f
  ive states of matter: solid, liquid, gas, plasma, and Bose-Einstein condens
  ate."}]z..........z.+.)langtrace_python_sdk.utils.with_root_span.K..t..7)Z7
  .F@!.`Y............*.LangtraceRootSpan0.9........A..8_....z.......         
#
T 172.240.1.1:37074 -> 172.240.1.4:3000 [AP] #15
  POST /api/trace HTTP/1.1..Host: localhost:3000..User-Agent: OTel-OTLP-Expor
  ter-Python/1.27.0..Accept-Encoding: gzip, deflate..Accept: */*..Connection:
   keep-alive..x-api-key: 7e758d1e57e90168fe85f8feafab61169fe671af0825264c20d
  331929aefd6df..Content-Type: application/x-protobuf..Content-Length: 1264..
  ........."..telemetry.sdk.language....python.%..telemetry.sdk.name....opent
  elemetry.!..telemetry.sdk.version....1.27.0....service.name....test.py....=
  .;langtrace_python_sdk.instrumentation.openai.instrumentation.....t..7)Z7.F
  @!.`Y....8 q.J...".........*.openai.chat.completions.create0.9H.......A.]4_
  ....J"..langtrace.service.name....OpenAIJ...langtrace.service.type....llmJ%
  ..langtrace.service.version....1.43.0J...langtrace.version....3.3.0J,..lang
  trace.sdk.name....langtrace-python-sdkJ(..url.full....https://api.openai.co
  m/v1/J...url.path..../chat/completionsJ...gen_ai.operation.name....chatJ'..
  gen_ai.request.model....gpt-3.5-turboJ...gen_ai.system....openaiJ-..gen_ai.
  response.model....gpt-3.5-turbo-0125J...gen_ai.usage.input_tokens....J ..ge
  n_ai.usage.output_tokens....J...gen_ai.usage.total_tokens...&Z|...........g
  en_ai.content.prompt.Z..gen_ai.prompt.I.G[{"role": "system", "content": "Ho
  w many states of matter are there?"}]Z... .2_......gen_ai.content.completio
  n.....gen_ai.completion......[{"role": "assistant", "content": "There are f
  ive states of matter: solid, liquid, gas, plasma, and Bose-Einstein condens
  ate."}]z..........z.+.)langtrace_python_sdk.utils.with_root_span.K..t..7)Z7
  .F@!.`Y............*.LangtraceRootSpan0.9........A..8_....z.......         
###
T 172.240.1.4:3000 -> 172.240.1.1:37074 [AP] #18
  HTTP/1.1 404 Not Found..vary: RSC, Next-Router-State-Tree, Next-Router-Pref
  etch..content-type: application/json..Date: Mon, 04 Nov 2024 23:28:17 GMT..
  Connection: keep-alive..Keep-Alive: timeout=5..Transfer-Encoding: chunked..
  ..                                                                         
#
T 172.240.1.4:3000 -> 172.240.1.1:37074 [AP] #19
  HTTP/1.1 404 Not Found..vary: RSC, Next-Router-State-Tree, Next-Router-Pref
  etch..content-type: application/json..Date: Mon, 04 Nov 2024 23:28:17 GMT..
  Connection: keep-alive..Keep-Alive: timeout=5..Transfer-Encoding: chunked..
  ..                                                                         
###
T 127.0.0.1:3000 -> 127.0.0.1:38024 [AP] #22
  HTTP/1.1 404 Not Found..vary: RSC, Next-Router-State-Tree, Next-Router-Pref
  etch..content-type: application/json..Date: Mon, 04 Nov 2024 23:28:17 GMT..
  Connection: keep-alive..Keep-Alive: timeout=5..Transfer-Encoding: chunked..
  ..                                                                         
##
T 172.240.1.4:3000 -> 172.240.1.1:37074 [AP] #24
  37..{"error":"Something went wrong while ingesting traces"}..0....         
#
T 172.240.1.4:3000 -> 172.240.1.1:37074 [AP] #25
  37..{"error":"Something went wrong while ingesting traces"}..0....         
###
T 127.0.0.1:3000 -> 127.0.0.1:38024 [AP] #28
  37..{"error":"Something went wrong while ingesting traces"}..0.... 
```

Could someone help me?

**Comment by karthikscale3** [comment]
Hi @lmorandini , could you try to set this env var and try again

```
LANGTRACE_API_HOST="http://localhost:3000/api/trace"
```

**Comment by lmorandini** [comment]
Thanks for the prompt reply @karthikscale3 .
I tried, but I did not see any change.

**Comment by alizenhom** [comment]
Hey @lmorandini

apologies for the issue you're currently facing, can you try out these steps
1. make sure to clear everything first by running `docker compose down -v`
2. make sure to build the latest image by running `docker compose up --build`
3. make sure the `os.getenv('LANGTRACE_API_KEY')` is actually retrieving the same api key you've just created

kindly try the above steps, if you're still having issues would be more than happy to help!

**Comment by pedrohmietlicki** [comment]
I'm having the same issue but with crewai, I don't receive any error response or some log

**Comment by alizenhom** [comment]
Hey @pedrohmietlicki 

Apologies for the issue you are currently experiencing

We are currently trying to triangulate the issue stated, can you kindly confirm if you're using the latest sdk version and if not which version you're currently using?

**Comment by pedrohmietlicki** [comment]
Of course!

`langtrace-python-sdk==3.3.1`
`crewai==0.76.9`

**Comment by lmorandini** [comment]
I tried to do a fresh build of the Docker Compose stack (`ocker compose up --build`), but the Next,js container did not start correctly:
````
Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
```

**Comment by lmorandini** [comment]
I was able to make it work with L:angTrace cloud after having unset the  ` LANGTRACE_API_HOST` env. var. However, I would like to use LangTrace in a hosted environment.

**Comment by karthikscale3** [comment]
Apologies for the issue. We are looking into this with high priority. Will update as soon as it's fixed.

**Comment by pedrohmietlicki** [comment]
@alizenhom  
I cloned the project but made some modifications to the setup. In the `docker-compose`, I only launched the ClickHouse and PostgreSQL services. Then, I built and ran the other components outside of Docker Compose. I can access the frontend, create projects, and view the API keys, but when I run the crew, nothing gets sent. There’s no error message, so I’m not sure what’s causing this issue.
![image](https://github.com/user-attachments/assets/5253ad35-fbf9-434c-b096-6a6e91834bb2)

**Comment by pedrohmietlicki** [comment]
Strangely, I just ran the project without the environment variables loaded, and I didn’t encounter any errors. I was expecting a connection failure, for example, but everything seems to run without issues.

**Comment by alizenhom** [comment]
hey @pedrohmietlicki,

i see from the logs, that you're writing spans to the console which means you have the `write_spans_to_console` flag set to `True` can you confirm it?

also, probably the environment variables loaded might be having a wrong `LANGTRACE_API_KEY`  which will point to a wrong project

**Comment by pedrohmietlicki** [comment]
I ran without this guy and but without environemt running yet.

**Comment by alizenhom** [comment]
nice, `exporting spans to custom host` means that traces are getting shipped correctly, can you confirm seeing traces on the dashboard?

**Comment by pedrohmietlicki** [comment]
I did with differents steps, but I test your way and recevice this error
I can send a video showing my steps
![image](https://github.com/user-attachments/assets/4dec440e-90e4-4509-9367-950826f43f4b)

**Comment by alizenhom** [comment]
yes @pedrohmietlicki kindly do that, this will be helpful to debug the issue.

**Comment by lpearl** [comment]
> 3\. os.getenv('LANGTRACE_API_KEY')

I have also tried these steps and have been unable to get traces to show up in the webapp but using the example code I can see its sent. I have tried entering in the key and host manual in the init and via a env variable.

```from langtrace_python_sdk import langtrace
from langtrace_python_sdk.utils.with_root_span import with_langtrace_root_span
# Paste this code after your langtrace init function

from dotenv import load_dotenv
import os

load_dotenv()

from openai import OpenAI

langtrace.init()

@with_langtrace_root_span()
def example():
    client = OpenAI()
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "How many states of matter are there?"
            }
        ],
    )
    print(response.choices[0].message.content)

example()
```

```
Initializing Langtrace SDK..
⭐ Leave our github a star to stay on top of our updates - https://github.com/Scale3-Labs/langtrace
Exporting spans to custom host: http://localhost:3000..
There are generally five states of matter: solid, liquid, gas, plasma, and Bose-Einstein condensate.
```

I have also tried building locally but get the following error:
```
Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
langtrace             |     at setupFsCheck (/app/node_modules/next/dist/server/lib/router-utils/filesystem.js:151:19)
langtrace             |     at async initialize (/app/node_modules/next/dist/server/lib/router-server.js:62:23)
langtrace             |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:249:36)
```

I'm running on M3 mac, let me know if there is anything I can do to help you debug this.

**Comment by alizenhom** [comment]
Hey @lpearl, sorry for the issue you're facing, apparently this is a repeating issue which we are struggling to replicate exactly.

can you kindly help and state exactly the steps you have taken to self host? kindly provide all details of your setup so we can try to replicate the issue and solve it quickly

apologies again for your issue, will prioritise fixing it asap!

**Comment by lpearl** [comment]
> Hey @lpearl, sorry for the issue you're facing, apparently this is a repeating issue which we are struggling to replicate exactly.
> 
> can you kindly help and state exactly the steps you have taken to self host? kindly provide all details of your setup so we can try to replicate the issue and solve it quickly
> 
> apologies again for your issue, will prioritise fixing it asap!

Thanks for the quick response. I am running Docker Desktop 4.35.1 on MacBook air m3. Before running I have cleared all the built images, volumes, and network.

1. `git clone https://github.com/Scale3-Labs/langtrace`

2. `cd langtrace`

Note: I need to change the host postgres port to 5436 since 5432 is in use on my network.

```
  postgres-db:
    container_name: langtrace-postgres
    image: postgres:16.2-bookworm
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
```

3. `docker compose up`

4. I go to http://localhost:3000 and login using the Admin email and password specified in the .env file.

5. I create a new project, Name: Test, Description: test, Project Type: default

(Is langgraph not supported in the default project type? When will it be supported?)

Note: once project is created I get the following error in the debug.

```
Error capturing telemetry events: Error: You must pass your PostHog project's api key.
langtrace             |     at /app/.next/server/app/api/project/route.js:1:10372
langtrace             |     at new T (/app/.next/server/app/api/project/route.js:1:10381)
langtrace             |     at new $ (/app/.next/server/app/api/project/route.js:1:26679)
langtrace             |     at G (/app/.next/server/app/api/project/route.js:1:32553)
langtrace             |     at Y (/app/.next/server/app/api/project/route.js:1:33761)
langtrace             |     at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36957
langtrace             |     at async eC.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552)
langtrace             |     at async eC.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38291)
langtrace             |     at async doRender (/app/node_modules/next/dist/server/base-server.js:1352:42)
langtrace             |     at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1574:28)
```

6. Click setup project and generate API key

7. Copy the API key and hit the x

8. Paste the API key in the .env variable in a new directory, python file is called test.py

9. I run the following code.

```
from langtrace_python_sdk import langtrace
from langtrace_python_sdk.utils.with_root_span import with_langtrace_root_span
# Paste this code after your langtrace init function

from dotenv import load_dotenv
import os

load_dotenv()

from openai import OpenAI

langtrace.init()

@with_langtrace_root_span()
def example():
    client = OpenAI()
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {
                "role": "system",
                "content": "How many states of matter are there?"
            }
        ],
    )
    print(response.choices[0].message.content)

example()
```

The following is returned by test.py

```
Initializing Langtrace SDK..
⭐ Leave our github a star to stay on top of our updates - https://github.com/Scale3-Labs/langtrace
Exporting spans to custom host: http://localhost:3000..
There are generally five states of matter: solid, liquid, gas, plasma, and Bose-Einstein condensate.

Process finished with exit code 0
```

I don't see anything show up on the web UI running on localhost:3000. Running `sudo ngrep -d any port 3000` I get the following.

```
T ::1:56193 -> ::1:3000 [AP] #9
  POST /api/trace HTTP/1.1..Host: localhost:3000..User-Agent: OTel-OTLP-Expor
  ter-Python/1.28.1..Accept-Encoding: gzip, deflate..Accept: */*..Connection:
   keep-alive..x-api-key: cc20420705a7c108b2d9b79f89ef04b2aa56f08f9e7a6d569cc
  c09e7d4d21abc..Content-Type: application/x-protobuf..Content-Length: 1298..
  ..                                                                         
#
T ::1:56193 -> ::1:3000 [AP] #10
  POST /api/trace HTTP/1.1..Host: localhost:3000..User-Agent: OTel-OTLP-Expor
  ter-Python/1.28.1..Accept-Encoding: gzip, deflate..Accept: */*..Connection:
   keep-alive..x-api-key: cc20420705a7c108b2d9b79f89ef04b2aa56f08f9e7a6d569cc
  c09e7d4d21abc..Content-Type: application/x-protobuf..Content-Length: 1298..
  ..                                                                         
##
T ::1:56193 -> ::1:3000 [AP] #12
  ....?.."..telemetry.sdk.language....python.%..telemetry.sdk.name....opentel
  emetry.!..telemetry.sdk.version....1.28.1.6..service.name.&.$/Users/lpearl/
  EosAiLangGraph/test.py.?..=.;langtrace_python_sdk.instrumentation.openai.in
  strumentation.?...s?..k?..??-.!....v@..`.?B"..?.?<..?*.openai.chat.complet
  ions.create0.98?by...A?...y...J"..langtrace.service.name....OpenAIJ...lang
  trace.service.type....llmJ%..langtrace.service.version....1.53.0J...langtra
  ce.version....3.3.3J,..langtrace.sdk.name....langtrace-python-sdkJ(..url.fu
  ll....https://api.openai.com/v1/J...url.path..../chat/completionsJ...gen_ai
  .operation.name....chatJ'..gen_ai.request.model....gpt-3.5-turboJ...gen_ai.
  system....openaiJ-..gen_ai.response.model....gpt-3.5-turbo-0125J...gen_ai.u
  sage.input_tokens....J ..gen_ai.usage.output_tokens....J...gen_ai.usage.tot
  al_tokens...&Z|..??by.....gen_ai.content.prompt.Z..gen_ai.prompt.I.G[{"role
  ": "system", "content": "How many states of matter are there?"}]Z?..0...y..
  ...gen_ai.content.completion.....gen_ai.completion......[{"role": "assistan
  t", "content": "There are five states of matter: solids, liquids, gases, pl
  asma, and Bose-Einstein condensates."}]z..........z.+.)langtrace_python_sdk
  .utils.with_root_span.K..s?..k?..??-.!.....?.?<..?*.LangtraceRootSpan0.9P]
  Zby...A.?..y...z.......                                                    
##
T ::1:56193 -> ::1:3000 [AP] #14
  ....?.."..telemetry.sdk.language....python.%..telemetry.sdk.name....opentel
  emetry.!..telemetry.sdk.version....1.28.1.6..service.name.&.$/Users/lpearl/
  EosAiLangGraph/test.py.?..=.;langtrace_python_sdk.instrumentation.openai.in
  strumentation.?...s?..k?..??-.!....v@..`.?B"..?.?<..?*.openai.chat.complet
  ions.create0.98?by...A?...y...J"..langtrace.service.name....OpenAIJ...lang
  trace.service.type....llmJ%..langtrace.service.version....1.53.0J...langtra
  ce.version....3.3.3J,..langtrace.sdk.name....langtrace-python-sdkJ(..url.fu
  ll....https://api.openai.com/v1/J...url.path..../chat/completionsJ...gen_ai
  .operation.name....chatJ'..gen_ai.request.model....gpt-3.5-turboJ...gen_ai.
  system....openaiJ-..gen_ai.response.model....gpt-3.5-turbo-0125J...gen_ai.u
  sage.input_tokens....J ..gen_ai.usage.output_tokens....J...gen_ai.usage.tot
  al_tokens...&Z|..??by.....gen_ai.content.prompt.Z..gen_ai.prompt.I.G[{"role
  ": "system", "content": "How many states of matter are there?"}]Z?..0...y..
  ...gen_ai.content.completion.....gen_ai.completion......[{"role": "assistan
  t", "content": "There are five states of matter: solids, liquids, gases, pl
  asma, and Bose-Einstein condensates."}]z..........z.+.)langtrace_python_sdk
  .utils.with_root_span.K..s?..k?..??-.!.....?.?<..?*.LangtraceRootSpan0.9P]
  Zby...A.?..y...z.......                                                    
###
T ::1:3000 -> ::1:56193 [AP] #17
  HTTP/1.1 404 Not Found..vary: RSC, Next-Router-State-Tree, Next-Router-Pref
  etch..content-type: application/json..Date: Wed, 13 Nov 2024 19:22:07 GMT..
  Connection: keep-alive..Keep-Alive: timeout=5..Transfer-Encoding: chunked..
  ..                                                                         
#
T ::1:3000 -> ::1:56193 [AP] #18
  HTTP/1.1 404 Not Found..vary: RSC, Next-Router-State-Tree, Next-Router-Pref
  etch..content-type: application/json..Date: Wed, 13 Nov 2024 19:22:07 GMT..
  Connection: keep-alive..Keep-Alive: timeout=5..Transfer-Encoding: chunked..
  ..                                                                         
###
T ::1:3000 -> ::1:56193 [AP] #21
  37..{"error":"Something went wrong while ingesting traces"}..0....         
#
T ::1:3000 -> ::1:56193 [AP] #22
  37..{"error":"Something went wrong while ingesting traces"}..0....  
```

Let me know if there is anything else you need.

**Comment by alizenhom** [comment]
@lpearl thankyou for your descriptive response, it has been a key helper to replicating the issue!
good news we have been able to replicate the issue and currently implementing a fix for it and will be released very soon!

@lmorandini @pedrohmietlicki apologies for the delay on this issue it will be resolved very soon!

**Comment by lpearl** [comment]
> @lpearl @lmorandini @pedrohmietlicki The fix is released, kindly proceed to delete any past images for langtrace and start from scratch, traces now should go through properly
> 
> will be more than happy to help if anyone faced any issues!
> 
> note: just discard the posthog api key warning, it's not harmful but will be addressed next

I confirm it's working on my end, thanks glad I could help.
